format = """
[](fg:#7aa2f7)\
$os\
[ ](fg:#7aa2f7 bg:#1a1b26)\
$directory\
[](fg:#1a1b26)\
$fill\
$git_branch\
$git_status\
$git_metrics\
\n$character\
"""

right_format = """
$cmd_duration
$lua
$rust
$time
"""